const MOTOR_DETAILS = [
  {
    id: 1,
    name: "KTM1",
    price: 100,
    available: true,
    rating: 4,
    image: "/src/images/foto3.png",
  },
  {
    id: 2,
    name: "KTM2",
    price: 120,
    available: true,
    rating: 5,
    image: "/src/images/foto3.png",
  },
  {
    id: 3,
    name: "KTM3",
    price: 90,
    available: false,
    rating: 3,
    image: "/src/images/foto3.png",
  },
  {
    id: 1,
    name: "BMW1",
    price: 100,
    available: true,
    rating: 4,
    image: "/src/images/bmw1.png",
  },
  {
    id: 2,
    name: "BMW2",
    price: 120,
    available: true,
    rating: 5,
    image: "/src/images/bmw1.png",
  },
  {
    id: 3,
    name: "BMW3",
    price: 90,
    available: false,
    rating: 3,
    image: "/src/images/bmw1.png",
  },

  {
    id: 1,
    name: "KAWA1",
    price: 100,
    available: true,
    rating: 4,
    image: "/src/images/kawa1.png",
  },
  {
    id: 2,
    name: "KAWA2",
    price: 120,
    available: true,
    rating: 5,
    image: "/src/images/kawa1.png",
  },
  {
    id: 3,
    name: "KAWA3",
    price: 90,
    available: false,
    rating: 3,
    image: "/src/images/kawa1.png",
  },

  {
    id: 1,
    name: "HONDA1",
    price: 100,
    available: true,
    rating: 4,
    image: "/src/images/honda1.png",
  },
  {
    id: 2,
    name: "HONDA2",
    price: 120,
    available: true,
    rating: 5,
    image: "/src/images/honda1.png",
  },
  {
    id: 3,
    name: "HONDA3",
    price: 90,
    available: false,
    rating: 3,
    image: "/src/images/honda1.png",
  },
  {
    id: 1,
    name: "HARLEYDAVIDSON1",
    price: 100,
    available: true,
    rating: 4,
    image: "/src/images/HarleyD1.png",
  },
  {
    id: 2,
    name: "HARLEYDAVIDSON2",
    price: 120,
    available: true,
    rating: 5,
    image: "/src/images/HarleyD1.png",
  },
  {
    id: 3,
    name: "HARLEYDAVIDSON3",
    price: 90,
    available: false,
    rating: 3,
    image: "/src/images/HarleyD1.png",
  },

  {
    id: 1,
    name: "YAMAHA1",
    price: 100,
    available: true,
    rating: 4,
    image: "/src/images/Yamaha1.png",
  },
  {
    id: 2,
    name: "YAMAHA2",
    price: 120,
    available: true,
    rating: 5,
    image: "/src/images/Yamaha1.png",
  },
  {
    id: 3,
    name: "YAMAHA3",
    price: 90,
    available: false,
    rating: 3,
    image: "/src/images/Yamaha1.png",
  },
];

export { MOTOR_DETAILS };
